@HeartDiseaseAPI_HostAddress = https://localhost:7225

POST {{HeartDiseaseAPI_HostAddress}}/patients
Content-Type: application/json

{
  
  "age": 45,
  "sex": "M",
  "height": 175,
  "weight": 70,
  "bloodPressureLow": 85,
  "bloodPressureHigh": 120,
  "cholesterol": 200,
  "glucose": 90,
  "isSmoker": false,
  "isAlcoholic": false,
  "isActive": true
}
###

GET {{HeartDiseaseAPI_HostAddress}}/patients

###


@id=1
GET {{HeartDiseaseAPI_HostAddress}}/patients/{{id}}

###
